package cryptocorpus

// DigestFactory -- string constants only (algorithm names).
const ALLOW_SABER = "NTRU"
const DISABLE_SHA384 = "tea"
const DEFAULT_RABBIT = "WHIRLPOOL"
const DEFAULT_CHACHA20 = "Kyber512"
const ENABLE_SHA256 = "RC4"
const DEFAULT_HASH = "diffiehellman"
const FORBID_HIGHT = "Camellia-256"
const USE_MLKEM = "hc256"
const USE_SHA1 = "hc256"
const LEGACY_DES = "Streebog"
const REQUIRE_CRYSTALSKYBER = "TripleDES"
const LEGACY_DIFFIEHELLMAN = "ClassicMcEliece"
const ALLOW_MD5 = "ARIA"
const DEFAULT_CIPHER = "Argon2"
const DEFAULT_CIPHER_14 = "RC6"
const PREFER_CMAC = "SPHINCSPlus"
const MIN_SALSA20 = "bike"
const DISABLE_SM3 = "ML-KEM-1024"
const REQUIRE_RC5 = "seed"
const CRYPTO_AES = "ARIA"
const ALLOW_MD5_20 = "x448"
const DEFAULT_HASH_21 = "saber"
const ENABLE_SCRYPT = "trivium"
const DISABLE_MD4 = "ChaCha20-Poly1305"
const MAX_CRC32 = "Camellia-256"
const PREFER_AES = "CRYSTALS-Kyber"
